# Generated by Django 3.1 on 2020-09-30 14:44

from django.db import migrations, models
import django.db.models.deletion
import utils.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', utils.models.fields.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', utils.models.fields.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('char_field', utils.models.fields.CharField(max_length=2555)),
            ],
            options={
                'verbose_name': 'OtherTestModel',
                'verbose_name_plural': 'Other Test Models',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', utils.models.fields.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', utils.models.fields.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('big_integer_field', utils.models.fields.BigIntegerField()),
                ('binary_field', utils.models.fields.BinaryField()),
                ('boolean_field', utils.models.fields.BooleanField()),
                ('char_field', utils.models.fields.CharField(max_length=2555)),
                ('char_field_with_choices', utils.models.fields.CharField(choices=[('HELLO', 'hello'), ('WORLD', 'world')], max_length=255)),
                ('date_field', utils.models.fields.DateField()),
                ('date_time_field', utils.models.fields.DateTimeField()),
                ('decimal_field', utils.models.fields.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_field', utils.models.fields.DurationField()),
                ('email_field', utils.models.fields.EmailField(default='julien@mefa.tech', max_length=254)),
                ('float_field', utils.models.fields.FloatField()),
                ('generic_ip_address_field', utils.models.fields.GenericIPAddressField()),
                ('integer_field', utils.models.fields.IntegerField()),
                ('null_boolean_field', utils.models.fields.NullBooleanField()),
                ('positive_integer_field', utils.models.fields.PositiveIntegerField()),
                ('positive_small_integer_field', utils.models.fields.PositiveSmallIntegerField()),
                ('slug_field', utils.models.fields.SlugField()),
                ('small_integer_field', utils.models.fields.SmallIntegerField()),
                ('text_field', utils.models.fields.TextField()),
                ('time_field', utils.models.fields.TimeField()),
                ('url_field', utils.models.fields.URLField()),
                ('uuid_field', utils.models.fields.UUIDField()),
                ('file_field', utils.models.fields.FileField(upload_to='')),
                ('image_field', utils.models.fields.ImageField(upload_to='')),
                ('foreign_key', utils.models.fields.ForeignKey(limit_choices_to={'char_field__icontains': 'hello'}, on_delete=django.db.models.deletion.CASCADE, related_name='fks', to='api.othertestmodel')),
                ('many_to_many_field', utils.models.fields.ManyToManyField(limit_choices_to={'char_field__icontains': 'world'}, related_name='many', to='api.OtherTestModel')),
                ('one_to_one_field', utils.models.fields.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='api.othertestmodel')),
            ],
            options={
                'verbose_name': 'TestModel',
                'verbose_name_plural': 'Test Models',
            },
        ),
        migrations.CreateModel(
            name='TestThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', utils.models.fields.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', utils.models.fields.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('other_test', utils.models.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.othertestmodel')),
                ('test', utils.models.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testmodel')),
            ],
            options={
                'verbose_name': 'TestThrough',
                'verbose_name_plural': 'TestThroughs',
            },
        ),
        migrations.AddField(
            model_name='othertestmodel',
            name='foreign_key',
            field=utils.models.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverse_fks', to='api.testmodel'),
        ),
        migrations.AddField(
            model_name='othertestmodel',
            name='many_to_many_field_with_through',
            field=utils.models.fields.ManyToManyField(related_name='reverse_many_with_through', through='api.TestThrough', to='api.TestModel'),
        ),
        migrations.AddField(
            model_name='othertestmodel',
            name='one_to_one_field',
            field=utils.models.fields.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverse_one', to='api.testmodel'),
        ),
    ]
