# Generated by Django 2.0.2 on 2018-04-09 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
                ('filename', models.CharField(editable=False, max_length=255, verbose_name='Name')),
                ('content_type', models.CharField(editable=False, max_length=255, verbose_name='Content Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medias/images', verbose_name='Image')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='medias/files', verbose_name='Fichier')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
            },
        ),
    ]
