SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax' 
SECURE_HSTS_SECONDS = 31536000
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
CSRF_COOKIE_HTTPONLY = True

COOKIE_PREFIX = '__Host-'
LANGUAGE_COOKIE_NAME = f'{COOKIE_PREFIX}django_language'
SESSION_COOKIE_NAME = f'{COOKIE_PREFIX}sessionid'
CSRF_COOKIE_NAME = f'{COOKIE_PREFIX}csrftoken'