from rest_framework.fields import (
    empty,
    BooleanField,
    NullBooleanField,
    CharField,
    UUIDField,
    EmailField,
    IntegerField,
    IPAddressField,
    FloatField,
    DecimalField,
    DateTimeField,
    DateField,
    TimeField,
    DurationField,
    ChoiceField,
    MultipleChoiceField,
    FileField,
    ListField,
    DictField,
    JSONField,
    ReadOnlyField,
    HiddenField,
    SlugField,
    SerializerMethodField,
    ModelField,
    URLField,
    ImageField,
)
from rest_framework.relations import (
    RelatedField,
    ManyRelatedField,
    PrimaryKeyRelatedField,
)
from rest_framework.serializers import BaseSerializer
from django.core.validators import (
    DecimalValidator,
    EmailValidator,
    MaxLengthValidator,
    MaxValueValidator,
    MinLengthValidator,
    MinValueValidator,
    RegexValidator,
    URLValidator,
)
from rest_framework.utils.field_mapping import ClassLookupDict

VALIDATORS_MAP = {
    DecimalValidator: {
        "name": "decimal",
        "values": {"decimal_places": "decimal_places", "max_digits": "max_digits",},
    },
    EmailValidator: {"name": "email", "values": {}},
    MaxLengthValidator: {"name": "maxlength", "values": {"maxlength": "limit_value"}},
    MaxValueValidator: {"name": "maxvalue", "values": {"maxvalue": "limit_value"}},
    MinLengthValidator: {"name": "minlength", "values": {"minlength": "limit_value"}},
    MinValueValidator: {"name": "minvalue", "values": {"minvalue": "limit_value"}},
    RegexValidator: {"name": "regex", "values": {"regex": "regex"}},
    URLValidator: {"name": "url", "values": {}},
}

SERIALIZER_FIELDS_MAP = {
    ImageField: {"type": "image", "values": {}},
    BooleanField: {"type": "boolean", "values": {}},
    NullBooleanField: {"type": "null_boolean", "values": {}},
    CharField: {"type": "char", "values": {}},
    UUIDField: {"type": "uuid", "values": {}},
    EmailField: {"type": "email", "values": {}},
    URLField: {"type": "url", "values": {}},
    IntegerField: {"type": "integer", "values": {}},
    FloatField: {"type": "float", "values": {}},
    DecimalField: {"type": "decimal", "values": {}},
    DateTimeField: {"type": "date_time", "values": {}},
    DateField: {"type": "date", "values": {}},
    IPAddressField: {"type": "ip_address", "values": {}},
    TimeField: {"type": "time", "values": {}},
    DurationField: {"type": "duration", "values": {}},
    ChoiceField: {"type": "choice", "values": {}},
    MultipleChoiceField: {"type": "choices", "values": {}},
    FileField: {"type": "file", "values": {}},
    ListField: {"type": "list", "values": {}},
    DictField: {"type": "dict", "values": {}},
    JSONField: {"type": "json", "values": {}},
    SlugField: {"type": "slug", "values": {}},
    ReadOnlyField: {"type": "read_only", "values": {}},
    HiddenField: {"type": "hidden", "values": {}},
    SerializerMethodField: {"type": "serializer_method", "values": {}},
    ModelField: {"type": "model", "values": {}},
    RelatedField: {"type": "related", "values": {},},
    ManyRelatedField: {"type": "many_related", "values": {},},
    PrimaryKeyRelatedField: {
        "type": "primary_key_related",
        "values": {
            # "model": get_related_meta,
            # "queryset": "queryset",
            # "filters": "queryset._deferred_filter",
        },
    },
    BaseSerializer: {"type": "base", "values": {}},
}

